# Generated by Django 5.0.2 on 2024-02-27 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='monthly_salary',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
