# Generated by Django 5.0.2 on 2024-02-27 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit_app', '0003_remove_loan_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='current_debt',
        ),
    ]
