# Generated by Django 5.0.2 on 2024-02-27 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_app', '0005_userloan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField(unique=True)),
                ('credit_score', models.IntegerField(default=0)),
                ('monthly_salary', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='LoanData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.FloatField()),
                ('interest_rate', models.FloatField()),
                ('tenure', models.IntegerField()),
                ('emi', models.FloatField(default=0.0)),
                ('approval', models.BooleanField(default=False)),
                ('corrected_interest_rate', models.FloatField(default=0.0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit_app.customer')),
            ],
        ),
    ]
