# Generated by Django 5.0.2 on 2024-02-27 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_app', '0004_remove_user_current_debt'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_users', to='credit_app.loan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_loans', to='credit_app.user')),
            ],
        ),
    ]
